### ISSUE TITLE
Cocoa: Starting MT via registered file type doesn't load the file

### ISSUE THREAD

**Issue by Deltafire** [Deltafire/MilkyTracker#18]
Example:

Double-click a .mod or .xm file, Milkytracker launches because it's registered as a handler for that file type, it doesn't load in the file that was double-clicked.

**Comment by dwhinham** [comment]
Thanks - I've fixed this in e2d61587dfc594bdacf840126a4730794af1c000.
If you have tabs enabled on MT, opening batches of multiple files also works, which is quite nice!

Please feel free to test and pull.

**Comment by Deltafire** [comment]
Looks good, works for me. Note that opening multiple files in tabs only works if "Load module in new tab" is enabled in the config panel.
