### ISSUE TITLE
Consider moving to CMake as a new build system

### ISSUE THREAD

**Issue by dwhinham** [Deltafire/MilkyTracker#39]
Today I created a build system for a basic project using CMake for the first time, and achieved what I needed to do in about 5 lines - really easy to set up.

Just thought I'd put this here as a suggestion for discussion - I think you even suggested it at Sundown. Not sure how much work it'd be to move from Autotools to CMake, but the automatic Xcode/VS/Makefile etc generation is absolutely brilliant.

Any thoughts?

**Comment by Deltafire** [comment]
I think if I was starting from scratch now I’d use CMake.  However, the Autotools scripts are already complete and working, so changing to CMake seems like it could be wasting effort.  Using it to generate XCode/VS sounds like a good idea, but I think this would require some effort to get it to a stage where we can use it to replace the existing VS/XCode project files (and is an additional step for anyone wishing to build Milkytracker).

However I have no objection if anyone wishes to undertake this task.

**Comment by sagamusix** [comment]
If you need even more meta build systems to consider about, Premake is pretty cool for generating makefiles/VS solutions/etc... built with lua, comes in a single executable, is configurable through lua...

**Comment by dwhinham** [comment]
CMake build system is in progress and ready for testing at https://github.com/Deltafire/MilkyTracker/tree/cmake.
