### ISSUE TITLE
ASIO audio not working in released build (Windows 8 64-bit)

### ISSUE THREAD

**Issue by aardvarkk** [Deltafire/MilkyTracker#4]
If I try to set up ASIO output in the current release (v0.90.86), I can't get it to work. I get the error message:

"Sound driver initialization failed. Try different settings or driver."

However, if I build the latest code myself in Visual Studio, I don't have the same problem. I haven't changed anything in the code... so I have no idea what could be wrong in the released version downloadable on the website?

For now, I will continue to use the version I build myself.

**Comment by Deltafire** [comment]
Closing this since it's most likely won't affect the next release.
