### ISSUE TITLE
master not building on Linux

### ISSUE THREAD

**Issue by taptap** [Deltafire/MilkyTracker#40]
After cloning, running `autoreconf -i` and `./configure` (which runs without any warning), make step fails:

g++ -DHAVE_CONFIG_H -I. -I../..  -D__LINUX_ALSASEQ__ -D__LINUX__ -DMILKYTRACKER -D_REENTRANT -I/usr/include/SDL2  -I../../src/milkyplay -I../../src/ppui -I../../src/tracker -I../../src/ppui/osinterface -I../../src/ppui/osinterface/sdl -I../../src/ppui/osinterface/posix -I../../src/midi/rtmidi -D__FORCE_SDL_AUDIO__  -g -O2 -MT posix/MidiReceiver_pthread.o -MD -MP -MF $depbase.Tpo -c -o posix/MidiReceiver_pthread.o posix/MidiReceiver_pthread.cpp &&\
mv -f $depbase.Tpo $depbase.Po
posix/MidiReceiver_pthread.cpp:34:20: fatal error: RtMidi.h: No such file or directory
 #include "RtMidi.h"

**Comment by taptap** [comment]
OS is GNU/Linux Gentoo amd64.

**Comment by dwhinham** [comment]
Hiya :)

We are moving to Git submodules for the libraries where possible, so somewhere in the cloned directory, do:

`git submodule init`
`git submodule update`

This should fetch RTMidi/RTAudio and allow you to build.

Let us know how you get on. :smile: 

(We should probably update the docs to this effect.)

**Comment by taptap** [comment]
Wooo~ o:
It builds!
Thanks! 

Documentation really needs an update. Make the project build was as simple as issue this two commands.

**Comment by dwhinham** [comment]
You're welcome - enjoy!
I've updated the README with a note about submodules (5801528d7a822cc787546d7f09625a247d8391da), so I'll close this issue now.

Cheers! :smiley:
