### ISSUE TITLE
Add appdata xml file and screenshot

### ISSUE THREAD

**Issue by muep** [Deltafire/MilkyTracker#42]
To better represent available applications in a general application installer, Fedora (and possibly some other GNU/Linux distributions) would want applications to ship with a bunch of metadata [1].

Fedora recommends package maintainers to add these to applications that do not already ship them, and send the metadata to the upstream project. This way different distributions will hopefully ship mostly the same description.

The main content that is needed are:
- The one-line summary
- The two or three paragraphs of description
- Screenshot(s)

I can write the metadata xml file based on existing package metadata we have. But since this data may end up in many distributions, I would like to ask the application authors if they want some particular things in the metadata. Otherwise, I'll just figure out something according to my taste and the available guidelines.

References:
[1] http://people.freedesktop.org/~hughsient/appdata/

**Comment by Deltafire** [comment]
Is this not the same thing?

https://github.com/Deltafire/MilkyTracker/blob/5801528d7a822cc787546d7f09625a247d8391da/resources/milkytracker.appdata

**Comment by muep** [comment]
Oh, indeed it seems to be. Nevermind :-)
